export const DATA_TEST_IDS = {
    signInForm: 'sign-in-form',
    loginInput: 'login-input',
    passwordInput: 'password-input',
    passwordVisibility: 'password-visibility-button',
    submitButton: 'submit-button',
    forgotPassword: 'forgot-password',
    signInErrorModal: 'sign-in-error-modal',
    closeButton: 'close-button',
    repeatButton: 'repeat-button',
    signUpProgress: 'sign-up-progress',
    signUpForm: 'sign-up-form',
    firstNameInput: 'first-name-input',
    lastNameInput: 'last-name-input',
    emailInput: 'email-input',
    confirmPasswordInput: 'confirm-password-input',
    sendEmailModal: 'send-email-modal',
    signUpSuccessModal: 'sign-up-success-modal',
    emailVerificationFailedModal: 'email-verification-failed-modal',
    verificationCodeModal: 'verification-code-modal',
    verificationCodeInput: 'verification-code-input-',
    resetCredentialsModal: 'reset-credentials-modal',
    errorNotification: 'error-notification',
    closeAlert: 'close-alert-button',
};
