export const APP_PATHS = {
    root: '/',
    category: ':category/',
    subcategory: ':category/:subcategory',
    recipePage: ':category/:subcategory/:recipeId',
    theJuiciest: '/the-juiciest',
    notFound: '/not-found',
    login: '/login',
    verification: '/verification',
    signUp: '/register',
    newRecipe: '/new-recipe',
    editRecipe: '/edit-recipe/:category/:subcategory/:recipeId',
    blogs: '/blogs',
    bloggerPage: '/blogs/:bloggerId',
    profile: '/profile',
    settings: '/profile/settings',
    editDraft: '/edit-draft/:draftId',
};
