export const pathNames = {
    // Салаты
    salads: 'Салаты',
    'meat-salads': 'Мясные салаты',
    'fish-salads': 'Рыбные салаты',
    'vegetable-salads': 'Овощные салаты',
    'warm-salads': 'Теплые салаты',

    // Закуски
    snacks: 'Закуски',
    'meat-snacks': 'Мясные закуски',
    'fish-snacks': 'Рыбные закуски',
    'vegetable-snacks': 'Овощные закуски',
    'warm-snacks': 'Теплые закуски',
    sandwiches: 'Бутерброды',
    fastfood: 'Фастфуд',

    // Первые блюда
    'first-dish': 'Первые блюда',
    'meat-soups': 'Мясные супы',
    'vegetable-soups': 'Овощные супы',
    broths: 'Бульоны',
    'cold-soups': 'Холодные супы',
    'diet-soups': 'Диетические супы',

    // Вторые блюда
    'second-dish': 'Вторые блюда',
    meat: 'Мясные',
    fish: 'Рыбные',
    vegetables: 'Овощные',
    'poultry-dish': 'Из птицы',
    mushrooms: 'Из грибов',
    offal: 'Из субпродуктов',
    couple: 'На пару',
    pelmeni: 'Пельмени, вареники',
    'flour-side-dishes': 'Мучные гарниры',
    'vegetable-side-dishes': 'Овощные гарниры',
    pizza: 'Пицца',
    sushi: 'Суши',

    // Десерты
    desserts: 'Десерты, выпечка',
    pancakes: 'Блины и оладьи',
    pies: 'Пироги и пончики',
    cakes: 'Торты',
    rolls: 'Рулеты',
    cupcakes: 'Кексы и маффины',
    syrniki: 'Сырники и ватрушки',
    'puff-dough': 'Из слоеного теста',
    'choux-dough': 'Из заварного теста',
    'yeast-dough': 'Из дрожжевого теста',
    buns: 'Булочки и сдоба',
    bread: 'Хлеб',
    'pizza-dough': 'Тесто на пиццу',
    creams: 'Кремы',

    // Гриль
    grilled: 'Блюда на гриле',
    beef: 'Говядина',
    pork: 'Свинина',
    'grilled-poultry': 'Птица на гриле',
    'grilled-fish': 'Рыба на гриле',
    'grilled-mushrooms': 'Грибы на гриле',
    'grilled-vegetables': 'Овощи на гриле',

    // Веганская кухня
    vegan: 'Веганская кухня',
    'vegan-snacks': 'Веганские закуски',
    'vegan-first-courses': 'Веганские первые блюда',
    'vegan-second-courses': 'Веганские вторые блюда',
    'side-dishes': 'Гарниры',
    bakery: 'Выпечка',
    'vegan-desserts': 'Веганские десерты',
    'vegan-bakery': 'Веганская выпечка',
    'raw-food-dishes': 'Сыроедческие блюда',
    'vegan-drinks': 'Веганские напитки',

    // Детские блюда
    child: 'Детские блюда',
    'child-first-courses': 'Детские первые блюда',
    'child-second-courses': 'Детские вторые блюда',
    'child-side-dishes': 'Детские гарниры',
    'child-bakery': 'Детская выпечка',
    'gluten-free': 'Без глютена',
    'sugar-free': 'Без сахара',
    'allergen-free': 'Без аллергенов',
    complementary: 'Блюда для прикорма',

    // Лечебное питание
    healthy: 'Лечебное питание',
    'childrens-diet': 'Детская диета',
    diet1: 'Диета №1',
    diet2: 'Диета №2',
    diet3: 'Диета №3',
    diet4: 'Диета №4',
    diet5: 'Диета №5',
    diet6: 'Диета №6',
    diet7: 'Диета №7',
    diet8: 'Диета №8',
    diet9: 'Диета №9',
    diet10: 'Диета №10',
    diet11: 'Диета №11',
    diet12: 'Диета №12',
    diet13: 'Диета №13',
    diet14: 'Диета №14',

    // Национальные кухни
    national: 'Национальные кухни',
    american: 'Американская кухня',
    armenian: 'Армянская кухня',
    greek: 'Греческая кухня',
    georgian: 'Грузинская кухня',
    italian: 'Итальянская кухня',
    spanish: 'Испанская кухня',
    chinese: 'Китайская кухня',
    mexican: 'Мексиканская кухня',
    'pan-asian': 'Паназиатская кухня',
    russian: 'Русская кухня',
    turkish: 'Турецкая кухня',
    french: 'Французская кухня',
    swedish: 'Шведская кухня',
    japanese: 'Японская кухня',
    other: 'Другая кухня',

    // Соусы
    sauces: 'Соусы',
    'meat-sauces': 'Соусы мясные',
    'cheese-sauces': 'Соусы сырные',
    marinades: 'Маринады',

    // Напитки
    drinks: 'Напитки',
    juices: 'Соки',
    'fresh-juices': 'Фреши',
    smoothie: 'Смузи',
    compotes: 'Компоты',
    kissels: 'Кисели',
    coffee: 'Кофе',
    'healing-drinks': 'Лечебные напитки',
    tea: 'Чай',
    kvass: 'Квас',
    cocktails: 'Коктейли',
    alcoholic: 'Алкогольные напитки',

    // Заготовки
    preparations: 'Заготовки',
    'meat-preparations': 'Мясные заготовки',
    'fish-preparations': 'Рыбные заготовки',
    'cucumbers-preparations': 'Заготовки из огурцов',
    'tomatoes-preparations': 'Заготовки из томатов',
    'mushrooms-preparations': 'Заготовки из грибов',
    'vegetable-preparations': 'Овощные заготовки',
    'salads-preparations': 'Заготовки салатов и икры',
    'fruit-preparations': 'Заготовки из фруктов и ягод',
};
