export enum EndpointNames {
    GET_RECIPES = 'getRecipes',
    GET_RECIPES_BY_CATEGORY = 'getRecipesByCategory',
    GET_CATEGORIES = 'getCategories',
    GET_RECIPES_WITH_PARAMS = 'getRecipesByParams',
    SIGNUP = 'signUp',
    LOGIN = 'login',
    FORGOT_PASSWORD = 'forgotPassword',
    VERIFY_OTP = 'verifyOTP',
    RESET_PASSWORD = 'resetPassword',
    CREATE_RECIPE = 'createRecipe',
    MEASURE_UNITS = 'measureUnits',
    CREATE_DRAFT = 'createDraft',
    DELETE_RECIPE = 'deleteRecipe',
    UPDATE_RECIPE = 'updateRecipe',
    GET_BLOGGERS = 'getBloggers',
    SUBSCRIBE_BLOGGER = 'SUBSCRIBE_BLOGGER',
    GET_BLOGGER_BY_ID = 'GET_BLOGGER_BY_ID',
    GET_USER_RECIPES = 'GET_USER_RECIPES',
    GET_PROFILE = 'GET_PROFILE',
    GET_STATISTIC = 'GET_STATISTIC',
    CREATE_NOTE = 'CREATE_NOTE',
    DELETE_NOTE = 'DELETE_NOTE',
    UPDATE_INFO = 'update_info',
    UPDATE_PASSWORD = 'update_password',
    DELETE_PROFILE = 'delete_profile',
    UPLOAD_PHOTO = 'upload_photo',
}
